/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mgrouse.shopbot;

import java.util.ArrayList;
import java.util.List;

import javax.security.auth.login.LoginException;

import com.github.mgrouse.shopbot.database.DataBaseTools;
import com.github.mgrouse.shopbot.database.DataBaseTools.DBASE;
import com.github.mgrouse.shopbot.listener.CommandHandler;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.Commands;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.interactions.commands.build.SlashCommandData;
import net.dv8tion.jda.api.requests.restaction.CommandListUpdateAction;


public class App
{
    private JDABuilder jdaBuilder;

    private JDA jda;

    private DataBaseTools dBase;

    public static void main(String[] args)
    {

	// Open Config file for Bot token etc.

	App app = new App();
	if (app.init())
	{
	    app.run();
	}
	// app.cleanUp();
    }

    public App()
    {

	// create JDA Builder
	jdaBuilder = JDABuilder.createDefault(Secret.BotToken);

	jdaBuilder.setStatus(OnlineStatus.ONLINE);
	jdaBuilder.setActivity(Activity.playing("D&D"));

    }

    public String getGreeting()
    {
	return "Hello World!";
    }

    public Boolean init()
    {
	// Init PROD DBase
	dBase = DataBaseTools.getInstance();
	dBase.init(DBASE.PROD);

	// Create the /commands
	List<SlashCommandData> slashCmds = new ArrayList<SlashCommandData>();

	// Import
	SlashCommandData data = Commands.slash("import", "Imports a PC from DND Beyond into the ShopBot system.");
	OptionData opts = new OptionData(OptionType.STRING, "id", "The numbers at the end of the PC's DNDB URL.");
	opts.setRequired(true);
	data.addOptions(opts);

	slashCmds.add(data);

	// Buy
	data = Commands.slash("character", "Prepares the named PC for shopping.");
	opts = new OptionData(OptionType.STRING, "name", "The name of the PC.");
	opts.setRequired(true);
	data.addOptions(opts);

	slashCmds.add(data);

	// Gold

	try
	{
	    jdaBuilder.addEventListeners(new CommandHandler(dBase));
	    jda = jdaBuilder.build();

	    CommandListUpdateAction action = jda.updateCommands();
	    action.addCommands(slashCmds);
	    action.complete();

	}
	catch (LoginException e)
	{
	    e.printStackTrace();
	}

	return true;
    }

    public void run()
    {

    }

    public void cleanUp()
    {
	// dBase.close();
    }
}
