/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mgrouse.shopbot;

import java.util.ArrayList;
import java.util.List;

import javax.security.auth.login.LoginException;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.Commands;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.interactions.commands.build.SlashCommandData;
import net.dv8tion.jda.api.requests.restaction.CommandListUpdateAction;


public class App
{
    private JDABuilder jdaBuilder;

    private JDA jda;


    // private EventListener evListener;

    public static void main(String[] args)
    {

	// Open Config file for Bot token etc.

	App app = new App();
	if (app.init())
	{
	    app.run();
	}
	app.cleanUp();
    }

    public App()
    {

	// create JDA Builder
	jdaBuilder = JDABuilder.createDefault(Secret.BotToken);

	jdaBuilder.setStatus(OnlineStatus.IDLE);
	jdaBuilder.setActivity(Activity.playing("D&D"));

    }

    public String getGreeting()
    {
	return "Hello World!";
    }

    public Boolean init()
    {
	List<SlashCommandData> slashCmds = new ArrayList<SlashCommandData>();
	// Create the /commands

	// Import
	SlashCommandData cImport = Commands.slash("import", "Imports a PC from DND Beyond into the ShopBot system.");

	OptionData cImportOpts = new OptionData(OptionType.STRING, "PC ID",
		"The numbers at the end of the PC's DNDB URL");
	cImportOpts.setRequired(true);


	cImport.addOptions(cImportOpts);
	slashCmds.add(cImport);

	// Buy


	try
	{
	    jda = jdaBuilder.build();

	    CommandListUpdateAction action = jda.updateCommands();
	    action.addCommands(slashCmds);

	}
	catch (LoginException e)
	{
	    e.printStackTrace();
	}

	return true;
    }

    public void run()
    {
	// jdaBuilder.addEventListeners(evListener);


    }

    public void cleanUp()
    {

    }
}
